steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mentormate-ms', '.']


  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mentormate-ms']


  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mentormate-ms'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mentormate-ms'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_NAME=${_DB_NAME},DB_USERNAME=${_DB_USERNAME},DB_PASSWORD=${_DB_PASSWORD},DB_SCHEMA=${_DB_SCHEMA}'


  # Print the service URL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: show-service-url
    entrypoint: bash
    args:
      - -c
      - |
        echo "************************************"
        echo "* Service URL:"
        gcloud run services describe mentormate-ms \
          --platform managed \
          --region us-central1 \
          --format='value(status.url)'
        echo "************************************"


substitutions:
  _DB_HOST: '35.226.150.221'
  _DB_PORT: '5432'
  _DB_NAME: 'glms1'
  _DB_USERNAME: 'postgres'
  _DB_PASSWORD: 'Sharade@WOWAPP_2025!!'
  _DB_SCHEMA: 'mentormate'
 




options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
  dynamic_substitutions: true


images:
  - 'gcr.io/$PROJECT_ID/mentormate-ms'


serviceAccount: 'projects/protean-horizon-457804-v7/serviceAccounts/mentormate-sa@protean-horizon-457804-v7.iam.gserviceaccount.com'
